### ISSUE TITLE
Change LSP to Mason ? 

### ISSUE THREAD

**Issue by realitymolder** [jpmcb/nvim-lua-conf#1]
Seems like LSP Installer (https://github.com/williamboman/nvim-lsp-installer) is deprecated, and they have moved to Mason LSP Installer. 
Did you think about moving to that instead?

**Comment by jpmcb** [comment]
+1 yes, I've been meaning to do this. I haven't need to move over since my existing setup was mostly fine. But will get to that shortly! Thanks! 😄

**Comment by realitymolder** [comment]
> +1 yes, I've been meaning to do this. I haven't need to move over since my existing setup was mostly fine. But will get to that shortly! Thanks! 😄

migration docs are here: 
https://github.com/williamboman/nvim-lsp-installer/discussions/876

**Comment by jpmcb** [comment]
Done! Long time coming 🙃 https://github.com/jpmcb/nvim-lua-conf/commit/8c7ca6147adefe28401f6763d4fa399a518dbe60
